const API_BASE_URL = "http://localhost:8080"
const API_OPENVIDU_URL = "http://localhost:4443"
const OPENVIDU_SERVER_SECRET = "MY_SECRET";

export { API_BASE_URL, API_OPENVIDU_URL, OPENVIDU_SERVER_SECRET }